// time fields are in milliseconds

export const CONFIG = Object.freeze({
    TYPING_TEXT: {
        AFTER_CHAR_TYPED_DELAY: 70,
        HEADER_ANIMATION_BEFORE_START_DELAY: 1000,
        CURSOR_ANIMATION_AFTER_TYPING_DELAY: 500,
        TEXT_FULLY_VISIBLE_TIME: 7000,
        TEXT_HIDDEN_TIME: 3000
    },
    HEADER: {
        MIN_LOAD_TIME: 2000,
        FADE_IN_TIME: 1500,
        FADE_IN_DELAY: 700
    },
    TIMELINE_START_YEAR: 1957,
    TIMELINE_END_YEAR: 1972
});